ArUco: aruco::Dictionary Class Reference
aruco::Dictionary Class Reference
This class represent a marker dictionary as a vector of MarkerCodes.
#include <highlyreliablemarkers.h>
Public Member Functions
bool fromFile (std::string filename)
Read dictionary from a .yml opencv file.
bool toFile (std::string filename)
Write dictionary to a .yml opencv file.
unsigned int distance (MarkerCode m, unsigned int &minMarker, unsigned int &minRot)
Return the distance of a marker to the dictionary, D(m,D) (Equation 7) Assign to minMarker the marker index in the dictionary with minimun distance to m Assign to minRot the rotation of minimun hamming distance.
unsigned int distance (MarkerCode m)
Return the distance of a marker to the dictionary, D(m,D) (Equation 7) Same method as distance(MarkerCode m, uint &minMarker, uint &minRot), except this doesnt return minMarker and minRot values.
unsigned int minimunDistance ()
Calculate the minimun distance between the markers in the dictionary (Equation 9)
Detailed Description
This class represent a marker dictionary as a vector of MarkerCodes.
Member Function Documentation
unsigned int aruco::Dictionary::distance (MarkerCode m, unsigned int & minMarker, unsigned int & minRot)
Return the distance of a marker to the dictionary, D(m,D) (Equation 7) Assign to minMarker the marker index in the dictionary with minimun distance to m Assign to minRot the rotation of minimun hamming distance.
The rotation refers to the marker passed as parameter, m
References aruco::MarkerCode::size().
Referenced by aruco::HighlyReliableMarkers::detect(), and minimunDistance().
unsigned int aruco::Dictionary::distance (MarkerCode m) [inline]
Return the distance of a marker to the dictionary, D(m,D) (Equation 7) Same method as distance(MarkerCode m, uint &minMarker, uint &minRot), except this doesnt return minMarker and minRot values.
bool aruco::Dictionary::fromFile (std::string filename)
Read dictionary from a .yml opencv file.
References aruco::MarkerCode::fromString().
Referenced by aruco::HighlyReliableMarkers::loadDictionary().
unsigned int aruco::Dictionary::minimunDistance ()
Calculate the minimun distance between the markers in the dictionary (Equation 9)
References distance().
Referenced by aruco::HighlyReliableMarkers::loadDictionary().
bool aruco::Dictionary::toFile (std::string filename)
Write dictionary to a .yml opencv file.
The documentation for this class was generated from the following files:
highlyreliablemarkers.h
highlyreliablemarkers.cpp