ArUco: ChromaticMask Class Reference
ChromaticMask Class Reference
#include <chromaticmask.h>
Public Member Functions
ChromaticMask ()
void setParams (unsigned int mc, unsigned int nc, double threshProb, aruco::CameraParameters CP, aruco::BoardConfiguration BC, vector< cv::Point3f > corners)
void setParams (unsigned int mc, unsigned int nc, double threshProb, aruco::CameraParameters CP, aruco::BoardConfiguration BC, float markersize=-1.)
void calculateGridImage (const aruco::Board &board)
cv::Mat getCellMap ()
cv::Mat getMask ()
void train (const cv::Mat &in, const aruco::Board &board)
void classify (const cv::Mat &in, const aruco::Board &board)
void classify2 (const cv::Mat &in, const aruco::Board &board)
void update (const cv::Mat &in)
bool isValid ()
void resetMask ()
Constructor & Destructor Documentation
ChromaticMask::ChromaticMask () [inline]
Member Function Documentation
void ChromaticMask::calculateGridImage (const aruco::Board & board)
References AvrgTime(), aruco::CameraParameters::CameraMatrix, aruco::CameraParameters::Distorsion, aruco::Board::Rvec, and aruco::Board::Tvec.
Referenced by classify(), and train().
void ChromaticMask::classify (const cv::Mat & in, const aruco::Board & board)
References calculateGridImage(), and resetMask().
void ChromaticMask::classify2 (const cv::Mat & in, const aruco::Board & board)
References aruco::CameraParameters::CameraMatrix, aruco::CameraParameters::CamSize, aruco::CameraParameters::Distorsion, fitRectToSize(), aruco::Board::Rvec, and aruco::Board::Tvec.
cv::Mat ChromaticMask::getCellMap () [inline]
cv::Mat ChromaticMask::getMask () [inline]
bool ChromaticMask::isValid () [inline]
void ChromaticMask::resetMask ()
References aruco::CameraParameters::CamSize.
Referenced by classify(), and setParams().
void ChromaticMask::setParams (unsigned int mc, unsigned int nc, double threshProb, aruco::CameraParameters CP, aruco::BoardConfiguration BC, vector< cv::Point3f > corners)
References aruco::CameraParameters::CamSize, aruco::MarkerDetector::enableErosion(), aruco::BoardDetector::getMarkerDetector(), aruco::MarkerDetector::LINES, resetMask(), aruco::MarkerDetector::setCornerRefinementMethod(), aruco::BoardDetector::setParams(), aruco::MarkerDetector::setThresholdParams(), and aruco::BoardDetector::setYPerpendicular().
Referenced by setParams().
void ChromaticMask::setParams (unsigned int mc, unsigned int nc, double threshProb, aruco::CameraParameters CP, aruco::BoardConfiguration BC, float markersize = -1.)
References setParams().
void ChromaticMask::train (const cv::Mat & in, const aruco::Board & board)
References calculateGridImage().
void ChromaticMask::update (const cv::Mat & in)
The documentation for this class was generated from the following files:
chromaticmask.h
chromaticmask.cpp