ArUco: aruco::HighlyReliableMarkers Class Reference
aruco::HighlyReliableMarkers Class Reference
Highly Reliable Marker Detector Class.
#include <highlyreliablemarkers.h>
Classes
class BalancedBinaryTree
Balanced Binary Tree for a marker dictionary.
Static Public Member Functions
static bool loadDictionary (Dictionary D)
Load the dictionary that will be detected or read it directly from file.
static bool loadDictionary (std::string filename)
static Dictionary & getDictionary ()
static int detect (const cv::Mat &in, int &nRotations)
Detect marker in a canonical image.
Detailed Description
Highly Reliable Marker Detector Class.
Member Function Documentation
int aruco::HighlyReliableMarkers::detect (const cv::Mat & in, int & nRotations) [static]
Detect marker in a canonical image.
Perform detection and error correction Return marker id in 0 rotation, or -1 if not found Assign the detected rotation of the marker to nRotation
References aruco::Dictionary::distance(), aruco::HighlyReliableMarkers::BalancedBinaryTree::findId(), and aruco::MarkerCode::getId().
static Dictionary& aruco::HighlyReliableMarkers::getDictionary () [inline, static]
bool aruco::HighlyReliableMarkers::loadDictionary (Dictionary D) [static]
Load the dictionary that will be detected or read it directly from file.
References aruco::HighlyReliableMarkers::BalancedBinaryTree::loadDictionary(), and aruco::Dictionary::minimunDistance().
Referenced by loadDictionary().
bool aruco::HighlyReliableMarkers::loadDictionary (std::string filename) [static]
References aruco::Dictionary::fromFile(), and loadDictionary().
The documentation for this class was generated from the following files:
highlyreliablemarkers.h
highlyreliablemarkers.cpp