ArUco: aruco::MarkerDetector Class Reference
aruco::MarkerDetector Class Reference
Main class for marker detection.
#include <markerdetector.h>
Public Types
enum ThresholdMethods { FIXED_THRES, ADPT_THRES, CANNY }
This set the type of thresholding methods available.
enum CornerRefinementMethod { NONE, HARRIS, SUBPIX, LINES }
Methods for corner refinement.
Public Member Functions
MarkerDetector ()
See.
~MarkerDetector ()
void detect (const cv::Mat &input, std::vector< Marker > &detectedMarkers, cv::Mat camMatrix=cv::Mat(), cv::Mat distCoeff=cv::Mat(), float markerSizeMeters=-1, bool setYPerperdicular=false) throw (cv::Exception)
Detects the markers in the image passed.
void detect (const cv::Mat &input, std::vector< Marker > &detectedMarkers, CameraParameters camParams, float markerSizeMeters=-1, bool setYPerperdicular=false) throw (cv::Exception)
Detects the markers in the image passed.
void setThresholdMethod (ThresholdMethods m)
Sets the threshold method.
ThresholdMethods getThresholdMethod () const
Returns the current threshold method.
void setThresholdParams (double param1, double param2)
Set the parameters of the threshold method We are currently using the Adptive threshold ee opencv doc of adaptiveThreshold for more info.
void getThresholdParams (double &param1, double &param2) const
Set the parameters of the threshold method We are currently using the Adptive threshold ee opencv doc of adaptiveThreshold for more info param1: blockSize of the pixel neighborhood that is used to calculate a threshold value for the pixel param2: The constant subtracted from the mean or weighted mean.
const cv::Mat & getThresholdedImage ()
Returns a reference to the internal image thresholded.
void setCornerRefinementMethod (CornerRefinementMethod method)
CornerRefinementMethod getCornerRefinementMethod () const
void setMinMaxSize (float min=0.03, float max=0.5) throw (cv::Exception)
Specifies the min and max sizes of the markers as a fraction of the image size.
void getMinMaxSize (float &min, float &max)
reads the min and max sizes employed
void enableErosion (bool enable)
Enables/Disables erosion process that is REQUIRED for chessboard like boards.
void setDesiredSpeed (int val)
Specifies a value to indicate the required speed for the internal processes.
int getDesiredSpeed () const
void setWarpSize (int val) throw (cv::Exception)
Specifies the size for the canonical marker image.
int getWarpSize () const
void setMakerDetectorFunction (int(*markerdetector_func)(const cv::Mat &in, int &nRotations))
Allows to specify the function that identifies a marker.
void pyrDown (unsigned int level)
Use an smaller version of the input image for marker detection.
void thresHold (int method, const cv::Mat &grey, cv::Mat &thresImg, double param1=-1, double param2=-1) throw (cv::Exception)
Thesholds the passed image with the specified method.
void detectRectangles (const cv::Mat &thresImg, vector< std::vector< cv::Point2f > > &candidates)
Detection of candidates to be markers, i.e., rectangles.
const vector< std::vector
< cv::Point2f > > & getCandidates ()
Returns a list candidates to be markers (rectangles), for which no valid id was found after calling detectRectangles.
bool warp (cv::Mat &in, cv::Mat &out, cv::Size size, std::vector< cv::Point2f > points) throw (cv::Exception)
Given the iput image with markers, creates an output image with it in the canonical position.
void refineCandidateLines (MarkerCandidate &candidate, const cv::Mat &camMatrix, const cv::Mat &distCoeff)
Refine MarkerCandidate Corner using LINES method.
Static Public Member Functions
static void glGetProjectionMatrix (CameraParameters &CamMatrix, cv::Size orgImgSize, cv::Size size, double proj_matrix[16], double gnear, double gfar, bool invert=false) throw (cv::Exception)
DEPRECATED!!! Use the member function in CameraParameters.
Detailed Description
Main class for marker detection.
Member Enumeration Documentation
enum aruco::MarkerDetector::CornerRefinementMethod
Methods for corner refinement.
Enumerator:
NONE
HARRIS
SUBPIX
LINES
enum aruco::MarkerDetector::ThresholdMethods
This set the type of thresholding methods available.
Enumerator:
FIXED_THRES
ADPT_THRES
CANNY
Constructor & Destructor Documentation
aruco::MarkerDetector::MarkerDetector ()
See.
References aruco::FiducidalMarkers::detect().
aruco::MarkerDetector::~MarkerDetector ()
Member Function Documentation
void aruco::MarkerDetector::detect (const cv::Mat & input, std::vector< Marker > & detectedMarkers, cv::Mat camMatrix = cv::Mat(), cv::Mat distCoeff = cv::Mat(), float markerSizeMeters = -1, bool setYPerperdicular = false) throw (cv::Exception)
Detects the markers in the image passed.
If you provide information about the camera parameters and the size of the marker, then, the extrinsics of the markers are detected
Parameters:
input input color image
detectedMarkers output vector with the markers detected
camMatrix intrinsic camera information.
distCoeff camera distorsion coefficient. If set Mat() if is assumed no camera distorion
markerSizeMeters size of the marker sides expressed in meters
setYPerperdicular If set the Y axis will be perpendicular to the surface. Otherwise, it will be the Z axis
void aruco::MarkerDetector::detect (const cv::Mat & input, std::vector< Marker > & detectedMarkers, CameraParameters camParams, float markerSizeMeters = -1, bool setYPerperdicular = false) throw (cv::Exception)
Detects the markers in the image passed.
If you provide information about the camera parameters and the size of the marker, then, the extrinsics of the markers are detected
Parameters:
input input color image
detectedMarkers output vector with the markers detected
camParams Camera parameters
markerSizeMeters size of the marker sides expressed in meters
setYPerperdicular If set the Y axis will be perpendicular to the surface. Otherwise, it will be the Z axis
void aruco::MarkerDetector::detectRectangles (const cv::Mat & thresImg, vector< std::vector< cv::Point2f > > & candidates)
Detection of candidates to be markers, i.e., rectangles.
This function returns in candidates all the rectangles found in a thresolded image
void aruco::MarkerDetector::enableErosion (bool enable) [inline]
Enables/Disables erosion process that is REQUIRED for chessboard like boards.
By default, this property is enabled
Referenced by ChromaticMask::setParams().
const vector<std::vector<cv::Point2f> >& aruco::MarkerDetector::getCandidates () [inline]
Returns a list candidates to be markers (rectangles), for which no valid id was found after calling detectRectangles.
CornerRefinementMethod aruco::MarkerDetector::getCornerRefinementMethod () const [inline]
int aruco::MarkerDetector::getDesiredSpeed () const [inline]
void aruco::MarkerDetector::getMinMaxSize (float & min, float & max) [inline]
reads the min and max sizes employed
Parameters:
min output size of the contour to consider a possible marker as valid (0,1]
max output size of the contour to consider a possible marker as valid [0,1)
const cv::Mat& aruco::MarkerDetector::getThresholdedImage () [inline]
Returns a reference to the internal image thresholded.
It is for visualization purposes and to adjust manually the parameters
ThresholdMethods aruco::MarkerDetector::getThresholdMethod () const [inline]
Returns the current threshold method.
void aruco::MarkerDetector::getThresholdParams (double & param1, double & param2) const [inline]
Set the parameters of the threshold method We are currently using the Adptive threshold ee opencv doc of adaptiveThreshold for more info param1: blockSize of the pixel neighborhood that is used to calculate a threshold value for the pixel param2: The constant subtracted from the mean or weighted mean.
int aruco::MarkerDetector::getWarpSize () const [inline]
void aruco::MarkerDetector::glGetProjectionMatrix (CameraParameters & CamMatrix, cv::Size orgImgSize, cv::Size size, double proj_matrix[16], double gnear, double gfar, bool invert = false) throw (cv::Exception) [static]
DEPRECATED!!! Use the member function in CameraParameters.
Given the intrinsic camera parameters returns the GL_PROJECTION matrix for opengl. PLease NOTE that when using OpenGL, it is assumed no camera distorsion! So, if it is not true, you should have undistor image
Parameters:
CamMatrix arameters of the camera specified.
orgImgSize size of the original image
size of the image/window where to render (can be different from the real camera image). Please not that it must be related to CamMatrix
proj_matrix output projection matrix to give to opengl
gnear,gfar,: visible rendering range
invert,: indicates if the output projection matrix has to yield a horizontally inverted image because image data has not been stored in the order of glDrawPixels: bottom-to-top.
void aruco::MarkerDetector::pyrDown (unsigned int level) [inline]
Use an smaller version of the input image for marker detection.
If your marker is small enough, you can employ an smaller image to perform the detection without noticeable reduction in the precision. Internally, we are performing a pyrdown operation
Parameters:
level number of times the image size is divided by 2. Internally, we are performing a pyrdown.
void aruco::MarkerDetector::refineCandidateLines (MarkerDetector::MarkerCandidate & candidate, const cv::Mat & camMatrix, const cv::Mat & distCoeff)
Refine MarkerCandidate Corner using LINES method.
Parameters:
candidate candidate to refine corners
void aruco::MarkerDetector::setCornerRefinementMethod (CornerRefinementMethod method) [inline]
Referenced by ChromaticMask::setParams().
void aruco::MarkerDetector::setDesiredSpeed (int val)
Specifies a value to indicate the required speed for the internal processes.
If you need maximum speed (at the cost of a lower detection rate), use the value 3, If you rather a more precise and slow detection, set it to 0.
Actually, the main differences are that in highspeed mode, we employ setCornerRefinementMethod(NONE) and internally, we use a small canonical image to detect the marker. In low speed mode, we use setCornerRefinementMethod(HARRIS) and a bigger size for the canonical marker image
void aruco::MarkerDetector::setMakerDetectorFunction (int(*)(const cv::Mat &in, int &nRotations) markerdetector_func) [inline]
Allows to specify the function that identifies a marker.
Therefore, you can create your own type of markers different from these employed by default in the library. The marker function must have the following structure:
int myMarkerIdentifier(const cv::Mat &in,int &nRotations);
The marker function receives the image 'in' with the region that migh contain one of your markers. These are the rectangular regions with black in the image.
As output your marker function must indicate the following information. First, the output parameter nRotations must indicate how many times the marker must be rotated clockwise 90 deg to be in its ideal position. (The way you would see it when you print it). This is employed to know always which is the corner that acts as reference system. Second, the function must return -1 if the image does not contains one of your markers, and its id otherwise.
void aruco::MarkerDetector::setMinMaxSize (float min = 0.03, float max = 0.5) throw (cv::Exception)
Specifies the min and max sizes of the markers as a fraction of the image size.
By size we mean the maximum of cols and rows.
Parameters:
min size of the contour to consider a possible marker as valid (0,1]
max size of the contour to consider a possible marker as valid [0,1)
void aruco::MarkerDetector::setThresholdMethod (ThresholdMethods m) [inline]
Sets the threshold method.
void aruco::MarkerDetector::setThresholdParams (double param1, double param2) [inline]
Set the parameters of the threshold method We are currently using the Adptive threshold ee opencv doc of adaptiveThreshold for more info.
Parameters:
param1,: blockSize of the pixel neighborhood that is used to calculate a threshold value for the pixel
param2,: The constant subtracted from the mean or weighted mean
Referenced by ChromaticMask::setParams().
void aruco::MarkerDetector::setWarpSize (int val) throw (cv::Exception)
Specifies the size for the canonical marker image.
A big value makes the detection slower than a small value. Minimun value is 10. Default value is 56.
void aruco::MarkerDetector::thresHold (int method, const cv::Mat & grey, cv::Mat & thresImg, double param1 = -1, double param2 = -1) throw (cv::Exception)
Thesholds the passed image with the specified method.
------------------------------------------------- Methods you may not need Thesde methods do the hard work. They have been set public in case you want to do customizations -------------------------------------------------
bool aruco::MarkerDetector::warp (cv::Mat & in, cv::Mat & out, cv::Size size, std::vector< cv::Point2f > points) throw (cv::Exception)
Given the iput image with markers, creates an output image with it in the canonical position.
Parameters:
in input image
out image with the marker
size of out
points 4 corners of the marker in the image in
Returns:
true if the operation succeed
The documentation for this class was generated from the following files:
markerdetector.h
markerdetector.cpp