ArUco: aruco::MarkerCode Class Reference
aruco::MarkerCode Class Reference
This class represent the internal code of a marker It does not include marker borders.
#include <highlyreliablemarkers.h>
Public Member Functions
MarkerCode (unsigned int n=0)
Constructor, receive dimension of marker.
MarkerCode (const MarkerCode &MC)
Copy Constructor.
unsigned int getId (unsigned int rot=0)
Get id of a specific rotation as the number obtaiend from the concatenation of all the bits.
bool get (unsigned int pos, unsigned int rot=0)
Get a bit value in a specific rotation.
std::vector< bool > getRotation (unsigned int rot)
Get the string of bits for a specific rotation.
void set (unsigned int pos, bool val)
Set the value of a vit in a specific rotation The marker is refered as a unidimensional string of bits, i.e.
unsigned int size ()
Return the full size of the marker (n*n)
unsigned int n ()
Return the value of marker dimension (n)
unsigned int selfDistance (unsigned int &minRot)
Return the self distance S(m) of the marker (Equation 8) Assign to minRot the rotation of minimun hamming distance.
unsigned int selfDistance ()
Return the self distance S(m) of the marker (Equation 8) Same method as selfDistance(uint &minRot), except this doesnt return minRot value.
unsigned int distance (MarkerCode m, unsigned int &minRot)
Return the rotation invariant distance to another marker, D(m1, m2) (Equation 6) Assign to minRot the rotation of minimun hamming distance.
unsigned int distance (MarkerCode m)
Return the rotation invariant distance to another marker, D(m1, m2) (Equation 6) Same method as distance(MarkerCode m, uint &minRot), except this doesnt return minRot value.
void fromString (std::string s)
Read marker bits from a string of "0"s and "1"s.
std::string toString ()
Convert marker to a string of "0"s and "1"s.
cv::Mat getImg (unsigned int pixSize)
Convert marker to a cv::Mat image of (pixSize x pixSize) pixels It adds a black border of one cell size.
Detailed Description
This class represent the internal code of a marker It does not include marker borders.
Constructor & Destructor Documentation
aruco::MarkerCode::MarkerCode (unsigned int n = 0)
Constructor, receive dimension of marker.
References n().
aruco::MarkerCode::MarkerCode (const MarkerCode & MC)
Copy Constructor.
Member Function Documentation
unsigned int aruco::MarkerCode::distance (MarkerCode m, unsigned int & minRot)
Return the rotation invariant distance to another marker, D(m1, m2) (Equation 6) Assign to minRot the rotation of minimun hamming distance.
The rotation refers to the marker passed as parameter, m
References getRotation().
unsigned int aruco::MarkerCode::distance (MarkerCode m) [inline]
Return the rotation invariant distance to another marker, D(m1, m2) (Equation 6) Same method as distance(MarkerCode m, uint &minRot), except this doesnt return minRot value.
void aruco::MarkerCode::fromString (std::string s)
Read marker bits from a string of "0"s and "1"s.
Referenced by aruco::Dictionary::fromFile().
bool aruco::MarkerCode::get (unsigned int pos, unsigned int rot = 0) [inline]
Get a bit value in a specific rotation.
The marker is refered as a unidimensional string of bits, i.e. pos=y*n+x
unsigned int aruco::MarkerCode::getId (unsigned int rot = 0) [inline]
Get id of a specific rotation as the number obtaiend from the concatenation of all the bits.
Referenced by aruco::HighlyReliableMarkers::detect().
cv::Mat aruco::MarkerCode::getImg (unsigned int pixSize)
Convert marker to a cv::Mat image of (pixSize x pixSize) pixels It adds a black border of one cell size.
References n().
std::vector<bool> aruco::MarkerCode::getRotation (unsigned int rot) [inline]
Get the string of bits for a specific rotation.
Referenced by distance().
unsigned int aruco::MarkerCode::n () [inline]
Return the value of marker dimension (n)
Referenced by getImg(), MarkerCode(), and set().
unsigned int aruco::MarkerCode::selfDistance (unsigned int & minRot)
Return the self distance S(m) of the marker (Equation 8) Assign to minRot the rotation of minimun hamming distance.
unsigned int aruco::MarkerCode::selfDistance () [inline]
Return the self distance S(m) of the marker (Equation 8) Same method as selfDistance(uint &minRot), except this doesnt return minRot value.
void aruco::MarkerCode::set (unsigned int pos, bool val)
Set the value of a vit in a specific rotation The marker is refered as a unidimensional string of bits, i.e.
pos=y*n+x This method assure consistency of the marker code:
The rest of rotations are updated automatically when performing a modification
The id values in all rotations are automatically updated too This is the only method to modify a bit value
References n().
unsigned int aruco::MarkerCode::size () [inline]
Return the full size of the marker (n*n)
Referenced by aruco::Dictionary::distance(), and toString().
std::string aruco::MarkerCode::toString ()
Convert marker to a string of "0"s and "1"s.
References size().
The documentation for this class was generated from the following files:
highlyreliablemarkers.h
highlyreliablemarkers.cpp