ArUco: aruco::BoardDetector Class Reference
aruco::BoardDetector Class Reference
This class detects AR boards Version 1.2 There are two modes for board detection.
#include <boarddetector.h>
Public Member Functions
BoardDetector (bool setYPerpendicular=false)
See discussion in.
void setParams (const BoardConfiguration &bc, const CameraParameters &cp, float markerSizeMeters=-1)
Use if you plan to let this class to perform marker detection too.
void setParams (const BoardConfiguration &bc)
float detect (const cv::Mat &im) throw (cv::Exception)
Detect markers, and then, look for the board indicated in setParams()
Board & getDetectedBoard ()
Returns a reference to the board detected.
MarkerDetector & getMarkerDetector ()
Returns a reference to the internal marker detector.
vector< Marker > & getDetectedMarkers ()
Returns the vector of markers detected.
float detect (const vector< Marker > &detectedMarkers, const BoardConfiguration &BConf, Board &Bdetected, cv::Mat camMatrix=cv::Mat(), cv::Mat distCoeff=cv::Mat(), float markerSizeMeters=-1) throw (cv::Exception)
Given the markers detected, determines if there is the board passed.
float detect (const vector< Marker > &detectedMarkers, const BoardConfiguration &BConf, Board &Bdetected, const CameraParameters &cp, float markerSizeMeters=-1) throw (cv::Exception)
void setYPerpendicular (bool enable)
By default, the Y axis is set to point up.
void setYPerperdicular (bool enable)
bool isYPerpendicular ()
void set_repj_err_thres (float Repj_err_thres)
Sets the threshold for reprjection test.
float get_repj_err_thres () const
Static Public Member Functions
static Board detect (const cv::Mat &Image, const BoardConfiguration &bc, const CameraParameters &cp, float markerSizeMeters=-1)
Static version (all in one).
Detailed Description
This class detects AR boards Version 1.2 There are two modes for board detection.
First, the old way. (You first detect markers with MarkerDetector and then call to detect in this class.
Second: New mode, marker detection is included in the class
  CameraParameters CP;
  CP.readFromFile(path_cp)
  BoardConfiguration BC;
  BC.readFromFile(path_bc);
  BoardDetector BD;
  BD.setParams(BC,CP); //or only BD.setParams(BC)
  //capture image
  cv::Mat im;
  capture_image(im);
  float prob=BD.detect(im);
  if (prob>0.3)
        CvDrawingUtils::draw3DAxis(im,BD.getDetectedBoard(),CP);
Constructor & Destructor Documentation
aruco::BoardDetector::BoardDetector (bool setYPerpendicular = false)
See discussion in.
See also:
enableRotateXAxis. Do not change unless you know what you are doing
Member Function Documentation
float aruco::BoardDetector::detect (const cv::Mat & im) throw (cv::Exception)
Detect markers, and then, look for the board indicated in setParams()
Returns:
value indicating the likelihood of having found the marker
Referenced by detect().
float aruco::BoardDetector::detect (const vector< Marker > & detectedMarkers, const BoardConfiguration & BConf, Board & Bdetected, cv::Mat camMatrix = cv::Mat(), cv::Mat distCoeff = cv::Mat(), float markerSizeMeters = -1) throw (cv::Exception)
Given the markers detected, determines if there is the board passed.
Parameters:
detectedMarkers result provided by aruco::ArMarkerDetector
BConf the board you want to see if is present
Bdetected output information of the detected board
camMatrix camera matrix with intrinsics
distCoeff camera distorsion coeff
camMatrix intrinsic camera information.
distCoeff camera distorsion coefficient. If set Mat() if is assumed no camera distorion
markerSizeMeters size of the marker sides expressed in meters
Returns:
value indicating the likelihood of having found the marker
float aruco::BoardDetector::detect (const vector< Marker > & detectedMarkers, const BoardConfiguration & BConf, Board & Bdetected, const CameraParameters & cp, float markerSizeMeters = -1) throw (cv::Exception)
Board aruco::BoardDetector::detect (const cv::Mat & Image, const BoardConfiguration & bc, const CameraParameters & cp, float markerSizeMeters = -1) [static]
Static version (all in one).
Static version (all in one)
Detects the board indicated
Parameters:
Image input image
bc the board you want to see if is present
cp camera parameters
markerSizeMeters size of the marker sides expressed in meters (not needed in the board is expressed in meters)
Returns:
Board detected
References detect(), getDetectedBoard(), and setParams().
float aruco::BoardDetector::get_repj_err_thres () const [inline]
Board& aruco::BoardDetector::getDetectedBoard () [inline]
Returns a reference to the board detected.
Referenced by detect().
vector<Marker>& aruco::BoardDetector::getDetectedMarkers () [inline]
Returns the vector of markers detected.
MarkerDetector& aruco::BoardDetector::getMarkerDetector () [inline]
Returns a reference to the internal marker detector.
Referenced by ChromaticMask::setParams().
bool aruco::BoardDetector::isYPerpendicular () [inline]
void aruco::BoardDetector::set_repj_err_thres (float Repj_err_thres) [inline]
Sets the threshold for reprjection test.
Pixels that after estimating the camera location projects 'repj_err_thres' pixels farther from its original location are discarded as outliers. By default it is set to -1, meaning that not reprojection test is performed
void aruco::BoardDetector::setParams (const BoardConfiguration & bc, const CameraParameters & cp, float markerSizeMeters = -1)
Use if you plan to let this class to perform marker detection too.
Referenced by detect(), and ChromaticMask::setParams().
void aruco::BoardDetector::setParams (const BoardConfiguration & bc)
void aruco::BoardDetector::setYPerpendicular (bool enable) [inline]
By default, the Y axis is set to point up.
However this is not the default operation mode of opencv, which produces the Z axis pointing up instead. So, to achieve this change, we have to rotate the X axis.
Referenced by ChromaticMask::setParams().
void aruco::BoardDetector::setYPerperdicular (bool enable) [inline]
The documentation for this class was generated from the following files:
boarddetector.h
boarddetector.cpp